@c -*-mode: texinfo-*-
\input texinfo   
@c %**start of header
@setfilename gngserver.info
@settitle GNGServer 
@setchapternewpage odd
@c %**end of header
@c @finalout
@headings 	    double

@include version.texi

@dircategory Programming
@direntry
* gngserver: (gngserver).		Server for the PBeM game GalaxyNG.
@end direntry

@ifinfo
This file documents gngserver.

Copyright 2005 Kenneth D. Weinert

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission notice
identical to this one except for the removal of this paragraph


@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by the Foundation.
@end ifinfo

@titlepage
@sp 10
@title GNGServer
@subtitle Edition @value{EDITION}, @value{UPDATED}
@subtitle $Id$
@author Kenneth D. Weinert
@author @email{madcoder42@users.sourceforge.net}

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2005 Kenneth D. Weinert

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by the Authors.
@end titlepage

@ifnottex
@c    name next   previous  up
@node Top, Introduction, (dir), (dir)
@top  GNGServer
@end ifnottex

@iftex
@unnumbered Forward
@end iftex

This is GNGServer.

@menu
* Introduction::
* Syntax::
* Index::
@end menu

@node Introduction
@chapter Introduction

GNGServer - a game server for the PBeM game galaxy.

@node Syntax
@chapter Syntax

@cindex tokeniser


@cindex syntax handlers

@page
@node Index
@unnumbered Index

@printindex cp

@c summarycontents
@contents
@bye

@ignore
Local Variables:
fill-column: 72
End:
@end ignore
